<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */

$template_directory = get_template_directory();

require ( $template_directory . '/core/includes/functions.php' );
require ( $template_directory . '/core/includes/theme-options.php' );
require ( $template_directory . '/core/includes/post-custom-meta.php' );
require ( $template_directory . '/core/includes/tha-theme-hooks.php' );
require ( $template_directory . '/core/includes/hooks.php' );
require ( $template_directory . '/core/includes/version.php' );
require ( $template_directory . '/core/includes/upsell/theme-upsell.php' );
?>

<?php register_new_royalslider_files(1); ?>

<?php
register_post_type( 'event', array(
  'labels' => array(
    'name' => 'Events',
    'singular_name' => 'Event',
   ),
  'description' => 'Upcoming Events',
  'public' => true,
  'menu_position' => 20,
  'supports' => array( 'title', 'editor', 'custom-fields' )
));
?>